# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/okunishi/PyJEMscript_in_okunishicalcPC/PyJEM_okunishi/PyJEMscript NEW/F200_change_STEM/STEMGUI3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
"""
 Copyright (C) <2021/10/25>  <Eiji Okunishi>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""    
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AUTOSTEM(object):
    def setupUi(self, AUTOSTEM):
        AUTOSTEM.setObjectName(_fromUtf8("AUTOSTEM"))
        AUTOSTEM.resize(240, 417)
        AUTOSTEM.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(30, 30, 30, 255));"))
        self.groupBox = QtGui.QGroupBox(AUTOSTEM)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 221, 371))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(30, 30, 30, 255));\n"
"color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(62, 183, 43, 255), stop:1 rgba(99, 252, 110, 255));\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(57, 210, 246, 255));"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nasalization"))
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.006, y2:0, stop:0 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));"))
        self.label_3.setFrameShape(QtGui.QFrame.Panel)
        self.label_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 310, 201, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(29)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.5, stop:0 rgba(90, 164, 254, 255), stop:1 rgba(150, 208, 255, 255));\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.006, y2:0, stop:0 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 141, 255, 255));\n"
""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nasalization"))
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.006, y2:0, stop:0 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));"))
        self.label_2.setFrameShape(QtGui.QFrame.Panel)
        self.label_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nasalization"))
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.006, y2:0, stop:0 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 255));"))
        self.label.setFrameShape(QtGui.QFrame.Panel)
        self.label.setFrameShadow(QtGui.QFrame.Sunken)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(110, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.006, y2:0, stop:0 rgba(255, 255, 255, 255));"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 140, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.006, y2:0, stop:0 rgba(255, 255, 255, 255));"))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.006, y2:0, stop:0 rgba(255, 255, 255, 255));"))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 201, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(90, 25, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 25, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 240, 201, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(140, 25, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(90, 25, 51, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.label_4 = QtGui.QLabel(AUTOSTEM)
        self.label_4.setGeometry(QtCore.QRect(26, 380, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MV Boli"))
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.5, y2:0.00568182, stop:0.00568182 rgba(237, 237, 237, 255), stop:0.988636 rgba(255, 255, 255, 255));"))
        self.label_4.setObjectName(_fromUtf8("label_4"))

        self.retranslateUi(AUTOSTEM)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), AUTOSTEM.clap)
        QtCore.QObject.connect(self.comboBox_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), AUTOSTEM.spot)
        QtCore.QObject.connect(self.comboBox_3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), AUTOSTEM.caml)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), AUTOSTEM.gotostem)
        QtCore.QObject.connect(self.radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), AUTOSTEM.haadfin)
        QtCore.QObject.connect(self.radioButton_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), AUTOSTEM.haadfout)
        QtCore.QObject.connect(self.radioButton_4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), AUTOSTEM.bfin)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), AUTOSTEM.bfout)
        QtCore.QMetaObject.connectSlotsByName(AUTOSTEM)

    def retranslateUi(self, AUTOSTEM):
        AUTOSTEM.setWindowTitle(_translate("AUTOSTEM", "AutoSTEM", None))
        self.groupBox.setTitle(_translate("AUTOSTEM", "Auto STEM", None))
        self.label_3.setText(_translate("AUTOSTEM", "Cam-L", None))
        self.pushButton.setText(_translate("AUTOSTEM", "Go to STEM", None))
        self.label_2.setText(_translate("AUTOSTEM", "Probe", None))
        self.label.setText(_translate("AUTOSTEM", "CL ap", None))
        self.comboBox.setItemText(0, _translate("AUTOSTEM", "Open", None))
        self.comboBox.setItemText(1, _translate("AUTOSTEM", "200um", None))
        self.comboBox.setItemText(2, _translate("AUTOSTEM", "100um", None))
        self.comboBox.setItemText(3, _translate("AUTOSTEM", "40um", None))
        self.comboBox.setItemText(4, _translate("AUTOSTEM", "10um", None))
        self.comboBox_3.setItemText(0, _translate("AUTOSTEM", "15mm", None))
        self.comboBox_3.setItemText(1, _translate("AUTOSTEM", "20mm", None))
        self.comboBox_3.setItemText(2, _translate("AUTOSTEM", "25mm", None))
        self.comboBox_3.setItemText(3, _translate("AUTOSTEM", "30mm", None))
        self.comboBox_3.setItemText(4, _translate("AUTOSTEM", "40mm", None))
        self.comboBox_3.setItemText(5, _translate("AUTOSTEM", "50mm", None))
        self.comboBox_3.setItemText(6, _translate("AUTOSTEM", "60mm", None))
        self.comboBox_3.setItemText(7, _translate("AUTOSTEM", "80mm", None))
        self.comboBox_3.setItemText(8, _translate("AUTOSTEM", "100mm", None))
        self.comboBox_3.setItemText(9, _translate("AUTOSTEM", "120mm", None))
        self.comboBox_3.setItemText(10, _translate("AUTOSTEM", "150mm", None))
        self.comboBox_3.setItemText(11, _translate("AUTOSTEM", "200mm", None))
        self.comboBox_3.setItemText(12, _translate("AUTOSTEM", "250mm", None))
        self.comboBox_3.setItemText(13, _translate("AUTOSTEM", "300mm", None))
        self.comboBox_3.setItemText(14, _translate("AUTOSTEM", "400mm", None))
        self.comboBox_3.setItemText(15, _translate("AUTOSTEM", "500mm", None))
        self.comboBox_3.setItemText(16, _translate("AUTOSTEM", "600mm", None))
        self.comboBox_3.setItemText(17, _translate("AUTOSTEM", "800mm", None))
        self.comboBox_3.setItemText(18, _translate("AUTOSTEM", "1000mm", None))
        self.comboBox_3.setItemText(19, _translate("AUTOSTEM", "1200mm", None))
        self.comboBox_3.setItemText(20, _translate("AUTOSTEM", "1500mm", None))
        self.comboBox_2.setItemText(0, _translate("AUTOSTEM", "   1", None))
        self.comboBox_2.setItemText(1, _translate("AUTOSTEM", "   2", None))
        self.comboBox_2.setItemText(2, _translate("AUTOSTEM", "   3", None))
        self.comboBox_2.setItemText(3, _translate("AUTOSTEM", "   4 ", None))
        self.comboBox_2.setItemText(4, _translate("AUTOSTEM", "   5", None))
        self.comboBox_2.setItemText(5, _translate("AUTOSTEM", "   6", None))
        self.comboBox_2.setItemText(6, _translate("AUTOSTEM", "   7", None))
        self.comboBox_2.setItemText(7, _translate("AUTOSTEM", "   8", None))
        self.comboBox_2.setItemText(8, _translate("AUTOSTEM", "   9", None))
        self.comboBox_2.setItemText(9, _translate("AUTOSTEM", " 10", None))
        self.groupBox_2.setTitle(_translate("AUTOSTEM", "HAADF ", None))
        self.radioButton.setText(_translate("AUTOSTEM", "IN", None))
        self.radioButton_2.setText(_translate("AUTOSTEM", "OUT", None))
        self.groupBox_3.setTitle(_translate("AUTOSTEM", "BF", None))
        self.radioButton_3.setText(_translate("AUTOSTEM", "OUT", None))
        self.radioButton_4.setText(_translate("AUTOSTEM", "IN", None))
        self.label_4.setText(_translate("AUTOSTEM", "PyJEM script by  ©Eiji Okunishi", None))

